### ISSUE TITLE
Nice work bro

### ISSUE THREAD

**Issue by MoeZilla** [MiyukiKun/telegram-rename-bot#1]
Good luck for exam

**Comment by MiyukiKun** [comment]
> Do u know how can I add download and upload in my repo ? With progress bar ?

**Comment by MiyukiKun** [comment]
> Do u know how can I add download and upload in my repo ? With progress bar ?

Just fork and deploy it, been using this myself for quite some time works perfectly with progressbar, try explaining your issue better

**Comment by Dark-Senpai** [comment]
> > Do u know how can I add download and upload in my repo ? With progress bar ?
> 
> Just fork and deploy it, been using this myself for quite some time works perfectly with progressbar, try explaining your issue better

Hey ! You are anime gallery admeme . NICE DUDE! Your anime quality is damn good. I am Dark [ • Savage • ] , I even messaged you many weeks ago on telegram .... 
Remembered??

**Comment by MiyukiKun** [comment]
Yup great, keep the issues tab for issues only tho, msg on tele if anything else

**Comment by Dark-Senpai** [comment]
> Yup great, keep the issues tab for issues only tho, msg on tele if anything else

Will remember it next time
